spring:
  application:
    name: bank-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false

server:
  port: 8081
logging:
  level:
    sl4j: INFO

security:
  token:
    secret-key: 53cr37
    expire-length: 3600000